<?php
/**
 * Run this once from the command line after importing schema.sql:
 *   php database/seed_users.php
 *
 * Creates the two demo accounts with password hashes generated by PHP's
 * own password_hash(), guaranteeing they verify correctly at login.
 */
require_once __DIR__ . '/../config/database.php';

$accounts = [
    ['full_name' => 'System Admin', 'email' => 'admin@library.com',   'password' => 'Admin@123',   'role' => 'admin',   'phone' => '0770000000'],
    ['full_name' => 'Demo Student', 'email' => 'student@library.com', 'password' => 'Student@123', 'role' => 'student', 'phone' => '0771111111'],
];

foreach ($accounts as $acc) {
    $check = $pdo->prepare("SELECT id FROM users WHERE email = ?");
    $check->execute([$acc['email']]);
    if ($check->fetch()) {
        echo "Skipped (already exists): {$acc['email']}\n";
        continue;
    }

    $hash = password_hash($acc['password'], PASSWORD_DEFAULT);
    $stmt = $pdo->prepare("INSERT INTO users (full_name, email, password, role, phone, status) VALUES (?, ?, ?, ?, ?, 'active')");
    $stmt->execute([$acc['full_name'], $acc['email'], $hash, $acc['role'], $acc['phone']]);
    echo "Created: {$acc['email']} / {$acc['password']} (role: {$acc['role']})\n";
}

echo "Done.\n";
